steps:
  # Step 0: Gatekeeper
  - name: 'bash'
    script: |
      if [[ "${_DEPLOY_CHECK}" == *"[deploy]"* ]]; then
        echo "Found [deploy] tag. Proceeding..."
      else
        echo "No [deploy] tag found. Skipping build."
        exit 0 # Use exit 1 if you want the build to show as 'Failed'
      fi
  # 1. Build the container image
  # We always build to ensure the code is valid/testable
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/expenses-app:latest', '.']

  # 2. Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/expenses-app:latest']

  # 3. Conditional Deploy to Cloud Run
  # This step only runs the 'gcloud run deploy' if the commit message contains '[deploy]'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if [[ "$(git log -1 --pretty=%B)" == *"[deploy]"* ]]; then
          echo "Deployment keyword [deploy] found! Proceeding with Cloud Run deployment..."
          gcloud run deploy expenses-app \
            --image gcr.io/$PROJECT_ID/expenses-app:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --service-account expenses-runner@surfn-peru.iam.gserviceaccount.com
        else
          echo "No [deploy] found in commit message. Skipping deployment."
          echo "Full commit message: $(git log -1 --pretty=%B)"
        fi

images:
  - 'gcr.io/$PROJECT_ID/expenses-app:latest'
