steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/expenses-app:$TAG_NAME', '.']

  # 2. Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/expenses-app:$TAG_NAME']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'expenses-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/expenses-app:$TAG_NAME'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'expenses-runner@surfn-peru.iam.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/expenses-app:$TAG_NAME'
