steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    env:
      - 'DOCKER_BUILDKIT=0' # Disables BuildKit to ensure legacy V2 manifest compatibility
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/expenses-app:$SHORT_SHA'
      - '.'

  # 2. Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/expenses-app:$SHORT_SHA']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'run'
      - 'deploy'
      - 'expenses-app'
      - '--image=gcr.io/$PROJECT_ID/expenses-app:$SHORT_SHA'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--service-account=expenses-runner@surfn-peru.iam.gserviceaccount.com'

images:
  - 'gcr.io/$PROJECT_ID/expenses-app:$SHORT_SHA'