createTime: '2026-02-06T01:09:32.234458283Z'
filename: cloudbuild.yaml
github:
  name: expenses
  owner: bwallerperu
  push:
    branch: ^main$
id: 498aeaf0-1ed1-4ff2-a537-0c48deb615b1
name: deploy-on-commit-msg
resourceName: projects/surfn-peru/locations/global/triggers/498aeaf0-1ed1-4ff2-a537-0c48deb615b1
substitutions:
  _COMMIT_MESSAGE: $(commit.message)
filter: build.substitutions['_COMMIT_MESSAGE'].matches(".*\\[deploy\\].*")  